# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YMPhotoBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YMPhotoBrowser
  pod 'Kingfisher', '~> 3.0'

  target 'YMPhotoBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YMPhotoBrowserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
